# 8bpl
# DO NOT CHANGE

FLECS_INC:=../../Libraries/flecs/include
CFLAGS += -I$(FLECS_INC) -I$(FLECS_INC)/flecs/ -I$(FLECS_INC)/flecs/modules -I$(FLECS_INC)/flecs/addons
LDLIBS += -lflecs

flecs_release: flecs
	-@echo Use libflecs release
	$(shell cp -P ../../Libraries/flecs/libflecs.a.release $(GAME_DIR_LIB)/libflecs.a)

flecs_debug: flecs
	-@echo Use libflecs debug
	$(shell cp -P ../../Libraries/flecs/libflecs.a.debug $(GAME_DIR_LIB)/libflecs.a)

flecs:
	$(shell mkdir -p $(GAME_DIR_LIB)/)
